### PR TITLE
Create nl.js

### PR DESCRIPTION
**Pull request by Raadsl**
Added the Dutch language. You still gotta add the option to use it (with the buttons etc)

### CODE REVIEW

**Comment by Raadsl** [comment]
:)

**Comment by umutxyp** [comment]
> Added the Dutch language. You still gotta add the option to use it (with the buttons etc)

Thank you for everything, but after you there were new additions to the language file, if you update them, I will think about the pull request.

**Comment by Raadsl** [comment]
I addedthe new messages!

**Comment by Raadsl** [comment]
Id  you add more strings in the future hit me up and I'll add the Dutch translation

**Comment by Raadsl** [comment]
If you add new words to the language files you can just add the english translation to nl.js and ill translate it:)

**Review by umutxyp — APPROVED** [review]

**Pull request merged**
