### PR TITLE
Add portuguese

### PR DESCRIPTION
**Pull request by contateste584394857**
Add portuguese language, with verified signature now

### CODE REVIEW

**Review by Fyxren — APPROVED** [review]
Looks good👍🏼

**Comment by contateste584394857** [comment]
@umutxyp

**Comment by umutxyp** [comment]
> @umutxyp

hey man, I don't know why, but no matter what I do, I couldn't combine the updates with the project. Please create a new pull req and post all updates at once.

**Comment by contateste584394857** [comment]
#57

**Pull request closed without merging**
