### PR TITLE
Add Traditional Chinese (zh_TW)

### PR DESCRIPTION
**Pull request by KageRyo**
I translate the message to Traditional Chinese.

### CODE REVIEW

**Comment by umutxyp** [comment]
> review zh_TW

hey thanks for the chinese. If you fill in the whole file correctly, ie provide a full chinese translation, I will approve your update and the update will be posted on both the official musicmaker bot and this project.

**Review by umutxyp — APPROVED** [review]

**Comment by KageRyo** [comment]
the zh_TW.js is finish

**Review by umutxyp — APPROVED** [review]

**Review by umutxyp — APPROVED** [review]

**Review by umutxyp — APPROVED** [review]

**Review by umutxyp — APPROVED** [review]

**Review by umutxyp — APPROVED** [review]

**Review by umutxyp — APPROVED** [review]

**Review by umutxyp — APPROVED** [review]

**Comment by umutxyp** [comment]
> the zh_TW.js is finish

hey man, I don't know why, but no matter what I do, I couldn't combine the updates with the project. Please create a new pull req and post all updates at once.

**Comment by KageRyo** [comment]
okay, I will do that at this saturday or sunday, thx

**Pull request merged**
